# enable embeded PostgreSQL
postgresql:
  enabled: true

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false

migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

scheduler:
#  env:
#   - name: _PIP_ADDITIONAL_REQUIREMENTS
#     value: "duckdb faker"
  extraVolumes:
    - name: dags
      hostPath:
        path: ${REPO_PATH}/dags/
        type: Directory
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
      readOnly: true

workers:
#  env:
#    - name: AIRFLOW_CONN_HTTP_DUMMYJSON
#      value: '{"conn_type": "http_dummyjson","host": "https://dummyjson.com","conn_type": "http"}'
#    - name: AIRFLOW_CONN_FS_DEFAULT
#      value: '{"conn_type": "fs_default","conn_type": "fs"}'
#    - name: _PIP_ADDITIONAL_REQUIREMENTS
#      value: "duckdb faker"
  extraVolumes:
    - name: dags
      hostPath:
        path: ${REPO_PATH}/dags
        type: Directory
    - name: data
      hostPath:
        path: ${REPO_PATH}/data
        type: Directory
  extraVolumeMounts:
    - name: dags
      mountPath: /opt/airflow/dags
      readOnly: true
    - name: data
      mountPath: /opt/airflow/data
      readOnly: false

airflow:
  connections:
    - conn_id: http_dummyjson
      conn_type: http
      host: https://dummyjson.com/

    - conn_id: local_fs
      conn_type: fs

